apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: exporter
  namespace: gf-space
spec:
  selector:
    matchLabels:
      name: exporter
  template:
    metadata:
      labels:
        name: exporter
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9100'
        prometheus.io/path: /metrics
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: exporter
        image: prom/node-exporter
        ports:
        - containerPort: 9100
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
      terminationGracePeriodSeconds: 30
      hostNetwork: true
      hostPID: true