apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: gf-space
spec:
  selector:
    app: prometheus
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: 30747
  type: LoadBalancer
