apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: gf-space
spec:
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: 'Asia/Tokyo'
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: grafana-vol
              mountPath: /var/lib/grafana
      volumes:
        - name: grafana-vol
          persistentVolumeClaim:
            claimName: grafana-pv-claim