apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: gf-space
spec:
  selector:
    app: grafana
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30748
  type: LoadBalancer